# permissions for end users to edit inboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: inbox-editor-role
rules:
- apiGroups:
  - api.kubeinbox.com
  resources:
  - inboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kubeinbox.com
  resources:
  - inboxes/status
  verbs:
  - get
