# permissions for end users to view inboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inbox-operator
    app.kubernetes.io/managed-by: kustomize
  name: inbox-viewer-role
rules:
- apiGroups:
  - api.kubeinbox.com
  resources:
  - inboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.kubeinbox.com
  resources:
  - inboxes/status
  verbs:
  - get
